### <span style='color:Red'>OneHotEncoder</span>
##### Converts categorical (text) data into numeric dummy variables.
##### sparse_output=True → returns a sparse matrix (default, memory efficient)
##### sparse_output=False → returns a dense NumPy array (easier to read and print)

In [3]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

data=pd.DataFrame({'color':['Red','Green','Blue']})
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(data[['color']])
print(encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


### <span style='color:Red'> StandardScaler </span>
###### Scales features so that each has mean = 0 and standard deviation = 1.
###### Useful for models like Logistic Regression, SVM, etc.
###### This process is also called Z-score normalization.
##### The Mathematical Formula

###### For each value x in a feature column:
##### z=x-μ/σ
###### Where:
###### x = original value
###### μ = mean of the column
###### σ = standard deviation of the column
###### z = standardized value

In [5]:
from sklearn.preprocessing import StandardScaler
import numpy as np
data=np.array([[10, 200],
               [20,400],
               [30, 600]])
scalar=StandardScaler()
scaled=scalar.fit_transform(data)
print(scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


#### <span style='color:Red'>RobustScaler</span>
###### Reduces the effect of outliers by using the median and IQR (interquartile range) instead of mean/std.
###### Mathematical Formula
#### z= (x-median)/IQR
##### where,
##### x=original value
##### median=median of the column
#### IQR=Q3-Q1
##### z=scaled value

In [8]:
from sklearn.preprocessing import RobustScaler
data=np.array([[10],[20],[10000]])
scalar=RobustScaler()
scaled=scalar.fit_transform(data)
print(scaled)

[[-0.002002]
 [ 0.      ]
 [ 1.997998]]


### Here outliner is 10000

### <span style='color: Red'>MinMaxScaler</span>
##### MinMaxScaler is a feature scaling technique that scales features to a fixed range, usually [0, 1].
### Mathematical Formula
##### Xscaled = (X-Xmin)/(Xmax-Xmin)
###### where,
#### x=original Value
#### Xmin=minimum value in the column
#### Xmax=maximum value in the column
#### Xscaled = scaled value in [0,1]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
data=np.array([[10],[20],[30]])
scalar=scalar.fit_transform(data)
